/*
 * generated by Xtext 2.20.0
 */
package org.qdt.quingo.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.qdt.quingo.QuingoRuntimeModule
import org.qdt.quingo.QuingoStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class QuingoIdeSetup extends QuingoStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new QuingoRuntimeModule, new QuingoIdeModule))
	}
	
}
