/*
 * generated by Xtext 2.20.0
 */
package org.qdt.quingo


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class QuingoStandaloneSetup extends QuingoStandaloneSetupGenerated {

	def static void doSetup() {
		new QuingoStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
