/*
 * generated by Xtext 2.20.0
 */
package org.qdt.quingo.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class QuingoUiModule extends AbstractQuingoUiModule {
}
